-- Ko-Sa content seed: Daily Activities, Wellness Packages, Stay Enhancements, Spa Treatments
-- Run this in your Supabase SQL Editor (supabase.com > project > SQL Editor)
-- After running, restart the dev server and run: npx prisma generate

-- ── CLEAR EXISTING ──────────────────────────────────────────────────────────
DELETE FROM "DailyActivity";
DELETE FROM "WellnessPackage";
DELETE FROM "StayEnhancement";
DELETE FROM "Treatment";

-- ── DAILY ACTIVITIES ────────────────────────────────────────────────────────

INSERT INTO "DailyActivity" (id, day, time, title, description, tag, "isFree", status, "sortOrder", "createdAt", "updatedAt") VALUES
  (gen_random_uuid(), 'MONDAY',    '8:00 AM',  'Morning Beach Yoga',                        'Start your week right. A gentle flow session on the sand as the sun rises over the Atlantic.',                                                                                                          'All levels welcome, just bring yourself.',        true, 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'MONDAY',    '5:00 PM',  'Sunset Watching and Photography Golden Hour','The Ghana sky puts on a show every evening. Grab your phone or camera and catch the Atlantic at its most golden.',                                                                                        'No filter needed.',                               true, 'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'TUESDAY',   '7:00 AM',  'Beach Walk',                                'The best way to wake up, barefoot on white sand with the Atlantic breeze in your face. A peaceful morning stroll along Ko-Sa''s beachfront to clear your head and fill your lungs.',                       null,                                              true, 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'TUESDAY',   '7:00 PM',  'Twi Lessons',                               'Pick up a few words of Ghana''s most spoken language. Learn to greet, bargain at the market and make locals smile.',                                                                                       'Fun, informal and surprisingly addictive.',       true, 'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'WEDNESDAY', '8:00 AM',  'Sunrise Meditation and Stretching',         'Begin your Wednesday with stillness. A guided meditation and gentle stretching session in Ko-Sa''s golden sand as the morning light filters through the palms.',                                          'Breathe in, slow down.',                          true, 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'WEDNESDAY', '7:00 PM',  'Games Night',                               'Board games, card games, laughter - the midweek social highlight at Ko-Sa. Pull up a chair, meet fellow guests and let the evening run away with you.',                                                  'Snacks welcome.',                                 true, 'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'THURSDAY',  '11:00 AM', 'Guided Walk to the Fishing Village',        'Step beyond the resort and into Ampenyi. Walk through the local fishing village with a Ko-Sa guide, meet the fishermen, see the boats and feel the real rhythm of life on Ghana''s coast.',              null,                                              true, 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'THURSDAY',  '5:00 PM',  'Walk in Ko-Sa Garden',                      'A slow, guided stroll through Ko-Sa''s lush garden grounds. Learn about the tropical plants, herbs and eco-landscaping that make Ko-Sa one of Ghana''s most distinctive green spaces.',                   null,                                              true, 'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'FRIDAY',    '8:00 AM',  'Sunrise Meditation and Stretching',         'Close out the week with intention. A grounding morning meditation and stretch session in Ko-Sa''s golden sand. The perfect way to arrive at Friday feeling clear, calm and present.',                     null,                                              true, 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'FRIDAY',    '3:00 PM',  'Drumming Lessons',                          'Feel the rhythm of Ghana. A hands-on introduction to West African drumming, no experience needed, just a willingness to move and laugh. One of Ko-Sa''s most popular afternoon sessions.',                null,                                              true, 'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'SATURDAY',  '7:00 AM',  'Tour of the Village',                       'An early morning walk through Ampenyi and the surrounding area with a Ko-Sa guide. See local life waking up, the market opening, fishing boats heading out - the real Ghana before the day gets busy.',  null,                                              true, 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'SATURDAY',  '7:00 PM',  'Twi Lessons',                               'Back by popular demand. Saturday evening Twi. Learn the phrases that will get you smiles, good deals and warm welcomes anywhere in Ghana.',                                                             'Casual, fun and genuinely useful.',               true, 'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'SUNDAY',    '10:00 AM', 'Family-Friendly Games',                     'Sunday morning is for everyone. A relaxed games session designed for guests of all ages - fun, low-key and a great way to spend the morning before checkout or a lazy beach afternoon.',                 null,                                              true, 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'SUNDAY',    '5:00 PM',  'Sunset Watching and Photography Golden Hour','End your weekend the Ko-Sa way. Watch the Atlantic turn gold as the sun drops below the horizon. Bring your camera, your drink and someone worth sharing a sunset with.',                                null,                                              true, 'PUBLISHED', 1, now(), now());

-- ── WELLNESS PACKAGES ────────────────────────────────────────────────────────

INSERT INTO "WellnessPackage" (id, slug, name, tagline, category, "durationLabel", "priceGhs", "originalPriceGhs", "priceNote", "couplePriceGhs", "couplePriceNote", inclusions, status, "sortOrder", "createdAt", "updatedAt") VALUES
(gen_random_uuid(), 'weekend-getaway',          'Weekend Getaway',          'Everything Accra is not. For two days.',                          'Leisure',     '2 Nights (Fri-Sun)',          2200, 2240,  'Solo',                    1900, 'Per Person (Couple)',    ARRAY['2 nights Garden View Double or Twin (upgradeable to Sea View)','Daily breakfast at Kosa Breeze restaurant','Complimentary 10-min welcome massage on arrival','1 activity of your choice: canoe ride, bead making, painting or horseback riding','Beach access with complimentary sunbed all weekend','Sunset drink voucher: Friday or Saturday evening at Kosa Breeze bar','Late check-out Sunday at 12 PM (standard)'], 'PUBLISHED', 0, now(), now()),
(gen_random_uuid(), 'the-ko-sa-reset',          'The Ko-Sa Reset',          'Five days of ocean air, healing rituals and stillness.',          'Wellness',    '5 Nights Minimum',           5800, 6496,  'Solo',                    5000, 'Per Person (Couple)',    ARRAY['5 nights Garden View Double (upgradeable to Sea View)','Daily breakfast at Kosa Breeze restaurant','Complimentary 10-min welcome massage on arrival','Ko-Sa Health Spa: Holistic Massage (60 min)','O2 Wellness: Herbal Detox Steam Ritual','O2 Wellness: Glow Polish Facial Ritual','Daily morning yoga and meditation (on schedule)','Ko-Sa kitchen cooking class: your choice of Ghanaian dish','Guided fishing village walk (Thursday)','Sunset beach setup: golden hour session','Welcome fresh juice and farewell seasonal fruit bowl'], 'PUBLISHED', 1, now(), now()),
(gen_random_uuid(), 'the-ko-sa-romance',        'The Ko-Sa Romance',        'Where the Atlantic meets your love story.',                       'Romance',     '2-3 Nights',                 5500, 6098,  'Per couple (2 nights)',   7000, 'Per couple (3 nights)', ARRAY['2 nights Deluxe or Luxury Double (Sea View)','Daily breakfast in bed or private beach breakfast','Complimentary 10-min welcome massage for both guests on arrival','Room decorated on arrival: rose petals, candles, welcome card','Welcome champagne or sparkling wine on arrival','Ko-Sa Health Spa: Couples Massage (60 min)','Private candle dinner on the beach: Kosa Breeze set menu for two','O2 Wellness: Herbal Detox Steam Ritual for two','O2 Wellness: Sunset Beach Setup with fresh juice and flowers','Late check-out at 2 PM (subject to availability)','Complimentary anniversary or honeymoon cake'], 'PUBLISHED', 2, now(), now()),
(gen_random_uuid(), 'the-proposal-experience',  'The Proposal Experience',  'The Atlantic as your backdrop. She will say yes.',                'Romance',     '1-2 Nights',                 3200, 3325,  '1 Night',                 5000, '2 Nights (Extended)',   ARRAY['1 night Luxury Double or Deluxe Double (Sea View)','Complimentary 10-min welcome massage for both guests','Private decorated beach setup: floral arch or table, candles, rose petals','Ko-Sa staff on standby for the proposal moment','Chilled sparkling wine: 2 bottles','Fresh tropical fruit platter','Ko-Sa staff photographer for the proposal: 30 minutes','Welcome card personally signed by Ko-Sa management','Champagne breakfast in bed the morning after','Option to extend stay: discounted second night available'], 'PUBLISHED', 3, now(), now()),
(gen_random_uuid(), 'birthday-celebration',     'Birthday Celebration',     'Because you deserve a birthday with the ocean.',                  'Celebration', '2-3 Nights',                 4500, 4760,  'Birthday Guest',          825,  'Extra Group Rooms (per room/night)', ARRAY['2 nights Garden or Sea View room (birthday person''s choice)','Daily breakfast at Kosa Breeze restaurant','Complimentary 10-min welcome massage on arrival','Personalised birthday cake from Ko-Sa kitchen','Room decorated on arrival: balloons, petals, birthday banner','Welcome cocktail or mocktail round for the group (up to 8 guests)','1 complimentary activity: drumming workshop, cooking class or canoe ride','Group beach bonfire setup: firewood, fairy lights, seating arranged','Birthday dinner at Kosa Breeze: dedicated table reserved'], 'PUBLISHED', 4, now(), now()),
(gen_random_uuid(), 'heritage-and-soul-retreat','Heritage and Soul Retreat', 'Come home to yourself. Ghana has always been waiting.',           'Culture',     '4 Nights',                   8500, 9750,  'Solo',                    7200, 'Per Person (Couple)',    ARRAY['4 nights Luxury Double or Twin (Sea View)','Daily breakfast at Kosa Breeze restaurant','Complimentary 10-min welcome massage on arrival','Welcome Ghanaian set dinner: Jollof Rice, Red Red or Groundnut Soup','Cape Coast Castle and Elmina Castle guided tours','Kakum National Park Tour','Drumming and Dancing Workshop','Batik Making class in Elmina','Guided City Tour and Street Food Tasting, Cape Coast','Twi language lesson: complimentary (Tuesday and Saturday)','Farewell beach sunset drink'], 'PUBLISHED', 5, now(), now()),
(gen_random_uuid(), 'the-ko-sa-day-pass',       'The Ko-Sa Day Pass',       'No room needed. Just a great day by the sea.',                   'Day Visit',   'Day Visit (10AM - 6PM)',      320,  null,  'Tier A (Beach and Lunch)', 550, 'Tier C (Full Wellness Day)', ARRAY['TIER A (GHC 320): Beach access and sunbed for the full day','TIER A: Set lunch at Kosa Breeze - 2 courses from Local Favourites menu','TIER A: Welcome fresh juice on arrival','TIER B (GHC 520): Everything in Tier A plus 1 activity of your choice: bead making, painting or horseback riding','TIER C (GHC 550): Everything in Tier B plus Ko-Sa Health Spa Swedish Massage or O2 Wellness ritual of your choice'], 'PUBLISHED', 6, now(), now()),
(gen_random_uuid(), 'the-slow-beach-escape',    'The Slow Beach Escape',    'No agenda. Just ocean, good food and time to breathe.',          'Eco',         '2-3 Nights',                 3800, 4580,  'Solo',                    2100, 'Per Person (Couple)',    ARRAY['2 nights minimum: Sea View Premium Room (Luxury Double)','Daily breakfast at Kosa Breeze restaurant','Complimentary 10-min welcome massage on arrival','Ko-Sa Health Spa: Swedish Massage (60 min)','Guided canoe ride with local Ampenyi fishermen','Ko-Sa garden walk and grounds tour','Village tour, Saturday morning (complimentary)','Beachside dinner for two: Kosa Breeze set menu','Welcome fresh juice on arrival','Sunset photography golden hour session','Bead making or painting class (guest''s choice)'], 'PUBLISHED', 7, now(), now());

-- ── STAY ENHANCEMENTS ────────────────────────────────────────────────────────

INSERT INTO "StayEnhancement" (id, category, name, description, "priceGhs", "priceTo", "priceNote", status, "sortOrder", "createdAt", "updatedAt") VALUES
  (gen_random_uuid(), 'Experiences & Celebrations', 'Private Beach Breakfast for Two',      null,                                          250,  null, null,           'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'Experiences & Celebrations', 'Couples Professional Photoshoot',      '1 hour on the beach',                         800,  null, null,           'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'Experiences & Celebrations', 'Beach Bonfire Setup',                  'Evening, firewood, fairy lights and seating', 350,  null, null,           'PUBLISHED', 2, now(), now()),
  (gen_random_uuid(), 'Experiences & Celebrations', 'Candle Dinner on the Beach',           'Kosa Breeze set menu for two',                800,  null, null,           'PUBLISHED', 3, now(), now()),
  (gen_random_uuid(), 'Experiences & Celebrations', 'Birthday or Celebration Cake',         'From Ko-Sa kitchen',                          400,  500,  null,           'PUBLISHED', 4, now(), now()),
  (gen_random_uuid(), 'Experiences & Celebrations', 'Room Decoration',                      'Rose petals, candles, banner',                200,  350,  null,           'PUBLISHED', 5, now(), now()),
  (gen_random_uuid(), 'Activities & Excursions',    'Ko-Sa Cooking Class',                  'Your choice of Ghanaian dish',                625,  null, null,           'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'Activities & Excursions',    'Drumming and Dancing Workshop',        null,                                          750,  null, null,           'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'Activities & Excursions',    'Cape Coast and Elmina Castle Tours',   null,                                          1000, null, 'per person',   'PUBLISHED', 2, now(), now()),
  (gen_random_uuid(), 'Activities & Excursions',    'Kakum National Park Tour',             null,                                          800,  null, 'per person',   'PUBLISHED', 3, now(), now()),
  (gen_random_uuid(), 'Activities & Excursions',    'Guided Canoe Ride',                    null,                                          600,  null, null,           'PUBLISHED', 4, now(), now()),
  (gen_random_uuid(), 'Activities & Excursions',    'Horseback Riding',                     null,                                          250,  null, null,           'PUBLISHED', 5, now(), now());

-- ── SPA TREATMENTS ───────────────────────────────────────────────────────────

INSERT INTO "Treatment" (id, slug, name, description, "durationMin", price, currency, category, status, "sortOrder", "createdAt", "updatedAt") VALUES
  (gen_random_uuid(), 'deepcore-massage',         'Deepcore Massage (45 min)',             'A unique combination of deep tissue, trigger points and energy flow. Releases deep tension while restoring the body''s natural energy pathways.',          45,   350,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'deepcore-massage-60',      'Deepcore Massage (60 min)',             'Extended deepcore session: deep tissue, trigger points and energy flow for a deeper release.',                                                              60,   400,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'couples-massage',          'Couples Massage (45 min)',              'Simultaneous massage for two in the same room. Share the experience of relaxation together.',                                                               45,   550,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 2, now(), now()),
  (gen_random_uuid(), 'couples-massage-60',       'Couples Massage (60 min)',              'Extended couples massage: simultaneous relaxation for two in the same room.',                                                                               60,   700,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 3, now(), now()),
  (gen_random_uuid(), 'swedish-massage',          'Swedish Massage (45 min)',              'Improves blood flow, reduces tension and enhances flexibility. A classic relaxation massage using long, flowing strokes.',                                  45,   300,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 4, now(), now()),
  (gen_random_uuid(), 'swedish-massage-60',       'Swedish Massage (60 min)',              'Extended Swedish massage for deeper relaxation and full-body tension release.',                                                                             60,   350,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 5, now(), now()),
  (gen_random_uuid(), 'holistic-massage',         'Holistic Massage (45 min)',             'Treats body, mind and spirit to balance energy and promote wellbeing. A whole-person approach to restoration.',                                            45,   330,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 6, now(), now()),
  (gen_random_uuid(), 'holistic-massage-60',      'Holistic Massage (60 min)',             'Extended holistic massage treating body, mind and spirit for complete restoration.',                                                                        60,   380,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 7, now(), now()),
  (gen_random_uuid(), 'reflexology',              'Reflexology (30 min)',                  'Pressure applied to feet, hands and ears to restore balance. A deeply relaxing treatment working on the body''s reflex points.',                           30,   200,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 8, now(), now()),
  (gen_random_uuid(), 'reflexology-45',           'Reflexology (45 min)',                  'Extended reflexology: pressure applied to feet, hands and ears for deeper balance restoration.',                                                            45,   250,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 9, now(), now()),
  (gen_random_uuid(), 'pedicure',                 'Pedicure',                             'Cleaning, exfoliating and moisturising of feet and toenails. A complete foot treatment to leave you refreshed.',                                            45,   150,  'GHS', 'Ko-Sa Health Spa', 'PUBLISHED', 10, now(), now()),
  (gen_random_uuid(), 'herbal-detox-steam',       'Herbal Detox Steam Ritual',            'Circulation, relaxation and cleansing. A deeply purifying steam ritual using herbal blends to detoxify and restore the body.',                             60,   264,  'GHS', 'O2 Wellness',      'PUBLISHED', 0, now(), now()),
  (gen_random_uuid(), 'glow-polish-facial',       'Glow Polish Facial Ritual',            'Radiance, hydration and skin refresh. A revitalising facial treatment to restore your natural glow.',                                                       60,   302,  'GHS', 'O2 Wellness',      'PUBLISHED', 1, now(), now()),
  (gen_random_uuid(), 'full-body-glow-polish',    'Full Body Glow Polish',                'Exfoliation, skin renewal and softening. A full-body scrub that leaves skin silky and luminous.',                                                           75,   672,  'GHS', 'O2 Wellness',      'PUBLISHED', 2, now(), now()),
  (gen_random_uuid(), '1-day-regenerative-escape','1-Day Regenerative Escape',            'Therapy, meal and wellness consultation. A full day of restoration combining treatments, nourishment and personalised wellness guidance.',                  480,  1200, 'GHS', 'O2 Wellness',      'PUBLISHED', 3, now(), now()),
  (gen_random_uuid(), '2-day-coastal-reset',      '2-Day Coastal Reset Retreat',          'Therapies, meals and guided wellness reset. Two days of immersive coastal wellness to fully recharge.',                                                     960,  2400, 'GHS', 'O2 Wellness',      'PUBLISHED', 4, now(), now()),
  (gen_random_uuid(), '3-day-full-renewal',       '3-Day Full Renewal Retreat',           'Immersive healing, meals and premium therapies. Three days of comprehensive renewal combining Ko-Sa''s best wellness offerings.',                           1440, 3600, 'GHS', 'O2 Wellness',      'PUBLISHED', 5, now(), now());
